FROM heroku/heroku:18

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN echo 'a028cba3dbb87635c2907c116de248fa93c29dff5e3f68d0f027c05b0f5e15ae  ./nodejs.deb' > node-file-lock.sha \
  && curl -s -o nodejs.deb https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/nodejs_12.18.1-deb-1nodesource1_amd64.deb \
  && shasum --check node-file-lock.sha
RUN apt-get install --assume-yes \
  ./nodejs.deb \ 
  openjdk-11-jdk-headless=11.0.7+10-2ubuntu2~18.04 \
  && mkdir ~/.sfdx-cli \
  && wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C ~/.sfdx-cli --strip-components 1 \
  && ~/.sfdx-cli/install \
  && rm nodejs.deb node-file-lock.sha

RUN apt-get autoremove --assume-yes \
  && apt-get clean --assume-yes \
  && rm -rf /var/lib/apt/lists/*

ENV SFDX_CONTAINER_MODE true
ENV DEBIAN_FRONTEND=dialog
ENV SHELL /bin/bash