FROM heroku/heroku:18

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN echo 'b78fc542858b83a96d712d6a2f493ae87e1af55040bc55fb68671af191016d19  ./nodejs.deb' > node-file-lock.sha \
  && curl -s -o nodejs.deb https://nodejs.org/dist/v12.18.1/node-v12.18.1-linux-arm64.tar.gz  \
  && shasum --check node-file-lock.sha
RUN apt-get install --assume-yes \
  ./nodejs.deb \ 
  openjdk-11-jdk-headless=11.0.7+10-2ubuntu2~18.04 \
  && mkdir ~/.sfdx-cli \
  && wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C ~/.sfdx-cli --strip-components 1 \
  && ~/.sfdx-cli/install \
  && rm nodejs.deb node-file-lock.sha

RUN apt-get autoremove --assume-yes \
  && apt-get clean --assume-yes \
  && rm -rf /var/lib/apt/lists/*

ENV SFDX_CONTAINER_MODE true
ENV DEBIAN_FRONTEND=dialog
ENV SHELL /bin/bash